server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        autoindex on;   # Enable directory browsing only for .html files
        autoindex_exact_size off;  # Display file size (optional)
        autoindex_localtime on;    # Display local time (optional)
        # Display only .html files
        autoindex_format html;  # Display directory listing in HTML format
        types {
            text/html html;
        }
        # Filter out .md files through regular expressions and prohibit them from being displayed in the directory index
        if ($request_uri ~* "\.md$") {
            return 404;  # When automatically indexed, .md files are not listed
        }

        # Disable .md files from appearing in the directory index, but they can still be accessed directly
        location ~* \.md$ {
            # For .md files, allow direct access
            default_type text/plain;  # Render .md files as plain text
            autoindex off;  # Disable .md files from appearing in directory lists

        }

    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
